aircraft: configs/aircraft_points.yaml
board:
  large_circle_dia_mm: 15
  name: SLS_300x250
  points_file: configs/board_points.yaml
  size_mm: 300x250
  small_circle_dia_mm: 7.5
  spacing_mm: 25
calibration:
  cx: 2028.6
  cy: 1574.0
  date: '2026-07-07'
  dist:
  - 0.105
  - -0.349
  - -0.0005
  - 0.0002
  - 0.0
  fx: 3282.7
  fy: 3392.6
  image_height: 3072
  image_width: 4096
  method: SLS_13img
  rms_px: 0.99
